repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
      - id: trailing-whitespace
        name: trim trailing whitespace
        description: This hook trims trailing whitespace on python files
        entry: trailing-whitespace-fixer


      - id: check-added-large-files
        name: check for large files.
        description: Prevent huge files from being commited accidentally.

      - id: check-merge-conflict
        name: check for merge conflict
        description: Prevent accidentally commiting files with merge conflicts.

      - id: check-yaml
        name: ensure yaml is valid.
        description: ensure that yaml is parsable

      - id: end-of-file-fixer
        name: fix end of files.
        description: Ensures that a file is either empty, or ends with one newline.

      - id: no-commit-to-branch
        name: ensure commit is not on master
        description: Prevent accidentally commiting to master.

      - id: autopep8-wrapper
        name: auto PEP8
        description: Applies pep8 to all the things

-   repo: git://github.com/pre-commit/mirrors-pylint
    sha: 'v1.7.4'
    hooks:
    -   id: pylint
        name: pylint

-   repo: https://github.com/JamesDommisse/frosted_hook
    sha: 'master'
    hooks:
      -  id: frosted
         name: frosted

-   repo: https://github.com/JamesDommisse/isort_hook
    sha: 'master'
    hooks:
      -  id: isort
         name: isort
